spring:
  application:
    name: eventservice
  datasource:
    url: jdbc:mysql://localhost:3306/events_db?useSSl=false&allowPublicKeyRetrieval=true&serverTimeZone=IST
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: event_user
    password: events_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080